insert into professors (id, first_name, last_name, profession) values (1, 'Nelly', 'Sotham', 'Physical Therapy Assistant');
insert into professors (id, first_name, last_name, profession) values (2, 'George', 'Kleint', 'Nurse');
insert into professors (id, first_name, last_name, profession) values (3, 'Nannie', 'McKennan', 'Staff Scientist');
insert into professors (id, first_name, last_name, profession) values (4, 'Kelbee', 'Demeza', 'Librarian');
insert into professors (id, first_name, last_name, profession) values (5, 'Ahmed', 'Branney', 'Operator');
insert into professors (id, first_name, last_name, profession) values (6, 'Norah', 'Fenck', 'Computer Systems Analyst III');
insert into professors (id, first_name, last_name, profession) values (7, 'Stefania', 'Poad', 'Geological Engineer');
insert into professors (id, first_name, last_name, profession) values (8, 'Jayme', 'Stedson', 'Research Nurse');
insert into professors (id, first_name, last_name, profession) values (9, 'Zerk', 'Adey', 'Media Manager III');
insert into professors (id, first_name, last_name, profession) values (10, 'Josias', 'Felix', 'Help Desk Technician');
insert into professors (id, first_name, last_name, profession) values (11, 'Orly', 'Crowson', 'Nuclear Power Engineer');
insert into professors (id, first_name, last_name, profession) values (12, 'Boris', 'Badby', 'Help Desk Technician');
insert into professors (id, first_name, last_name, profession) values (13, 'Kaylyn', 'Montel', 'Staff Scientist');
insert into professors (id, first_name, last_name, profession) values (14, 'Ban', 'Ramble', 'VP Accounting');
insert into professors (id, first_name, last_name, profession) values (15, 'Gabbey', 'Herley', 'Staff Accountant I');
insert into professors (id, first_name, last_name, profession) values (16, 'Corabelle', 'Merrison', 'Environmental Tech');
insert into professors (id, first_name, last_name, profession) values (17, 'Tallie', 'McInnery', 'Administrative Assistant III');
insert into professors (id, first_name, last_name, profession) values (18, 'Gawen', 'Catonne', 'Executive Secretary');
insert into professors (id, first_name, last_name, profession) values (19, 'Silvie', 'Handaside', 'Account Representative IV');
insert into professors (id, first_name, last_name, profession) values (20, 'Aidan', 'Whitmarsh', 'Automation Specialist III');